logging:
  level:
    root: INFO
spring:
  profiles:
    active: jpa
  h2:
    console:
      enabled: true
security:
  basic:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: jpa
  statemachine:
    data:
      mongo:
        repositories:
          enabled: false
      redis:
        repositories:
          enabled: false
---
spring:
  config:
    activate:
      on-profile: mongo
  statemachine:
    data:
      jpa:
        repositories:
          enabled: false
      redis:
        repositories:
          enabled: false
---
spring:
  config:
    activate:
      on-profile: redis
  statemachine:
    data:
      jpa:
        repositories:
          enabled: false
      mongo:
        repositories:
          enabled: false
